# Use postgres/example user/password credentials
version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=user_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD= root
    ports:
      - "5433:5433"
